#!/usr/bin/env bash

sudo apt install r-base r-base-dev -y

sudo apt-get install libpq-dev

sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
sudo apt-get update
sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev 

sudo -i R 

install.packages("sf")

install.packages("RPostgreSQL")

install.packages("raster")

install.packages("dplyr")

install.packages("readr")

install.packages("magrittr")

install.packages("stringr")




